classes/ui/class.ui.notice.php, readme.txt, views/packages/details/detail.php, views/packages/main/s1.setup2.php, views/packages/main/s3.build.php, views/tools/diagnostics/support.php
Provided several string fixes original found by @webaware when we translated for english variants.
=> Fix Strings

classes/package/class.pack.database.php, classes/package/class.pack.php
duplicator_lite_build_before_start 	args 	$package 
duplicator_lite_build_start 		args 	$package 
duplicator_lite_build_fail		args 	$package 
duplicator_lite_build_completed		args 	DUP_PRO_Package $package 
duplicator_lite_build_database_before_start	args 	 $package
duplicator_lite_build_database_start		args 	$package
duplicator_lite_build_database_completed	args 	$package
duplicator_lite_build_database_fail		args 	 $package
=> Add duplicator hooks

installer/dup-installer/classes/utilities/class.u.php
=> PR-Tickets: Deserializing active plugins erroring out on some customer machines

classes/class.archive.config.php, classes/package/class.pack.installer.php, installer/dup-installer/classes/config/class.archive.config.php, installer/dup-installer/ctrls/ctrl.s3.php, installer/dup-installer/views/view.s3.php
=> LT: EXE Step 3 wp-config options should be automatically ticked as per wp-config.php file

installer/dup-installer/classes/utilities/class.u.php, installer/dup-installer/ctrls/ctrl.s3.php
=> PR LT: EXE WPCACHEHOME path should be replaced if keep cache home path checkbox ticked

installer/dup-installer/classes/class.engine.php, installer/dup-installer/classes/utilities/class.u.php
search and replace on non object base64 strings
=> LT: Migration Report Issues

views/packages/main/s2.scan3.php
…ilter checkbox is not checked
=> PR: Quick filter button should be validated or disabled when any filter checkbox is not checked

views/packages/main/s3.build.php
=> LT: Mamp safari can't download when click on the One click download button

classes/package/class.pack.php
Now the function **not_active_files_tmp_cleanup** considers files that start with NameHash as part of the package regardless of their type.
=> 20181209 al lt bug on zip archive build

classes/package/class.pack.archive.php
task: LT: Tick - Symlink and filters
Filter link logic changed. See task
=> 20181222 al lt symlink and filters

installer/installer.tpl
=> LT-EXE: Detect when zip archive doesn't have dup-installer dir in it when installing

classes/package/class.pack.archive.php
Trello card: https://trello.com/c/hrKokwQX
=> PR-Tickets: 2 customers experiencing same build problem introduced in 3.8.0

installer/dup-installer/php.ini
Trello card: https://trello.com/c/LHWuQayE
=> LT: PR Ticket Installer 500 error

installer/dup-installer/classes/config/class.wp.config.tranformer.php
Trello cards: 
* https://trello.com/c/1j64mVzK
*  https://trello.com/c/xYymi17u
=> LT: 2 Tickets: Error establishing a database connection && Normalize the newline to prevent an issue coming from OSX

installer/dup-installer/classes/class.csrf.php, installer/dup-installer/main.installer.php, installer/dup-installer/views/view.s1.base.php, lib/dup_archive/daws/daws.php
Trello card: https://trello.com/c/lwuE2BDB
=> LT: Issue with DupArchive

installer/dup-installer/ctrls/ctrl.s2.base.php, installer/dup-installer/ctrls/ctrl.s3.php, installer/dup-installer/views/view.s3.php
Trello card: https://trello.com/c/76NKOJSY
=> LT: Complex DB pass is not working in installer

classes/package/class.pack.database.php, installer/dup-installer/ctrls/ctrl.s2.base.php, installer/dup-installer/ctrls/ctrl.s2.dbinstall.php, installer/dup-installer/views/view.s2.base.php
Trello card: https://trello.com/c/3uupEumo
=> LT Exe: Verify db install by row count

installer/dup-installer/classes/utilities/class.u.php, installer/dup-installer/ctrls/ctrl.s1.php
log improved
if dup-folder not fount continue with subfolder empty
=> installer extractor bugfix

installer/dup-installer/ctrls/ctrl.s2.dbinstall.php, installer/dup-installer/views/view.s2.base.php
Trello card: https://trello.com/c/uvSZ5AFw
=> LT: Installer step 2 JS errors

classes/package/class.pack.database.php, installer/dup-installer/ctrls/ctrl.s2.base.php, installer/dup-installer/ctrls/ctrl.s2.dbinstall.php
Trello card: https://trello.com/c/uvSZ5AFw
=> LT: Installer step 2 JS errors Part 2

installer/dup-installer/classes/class.logging.php, installer/dup-installer/main.installer.php, installer/dup-installer/views/view.s1.base.php
Trello card: https://trello.com/c/IntSf8VN
=> LT: EXE DupArchive "already installed" checking flow change

installer/dup-installer/classes/utilities/class.u.php
Trello card: https://trello.com/c/f8cUh502
=> LT: LT Ticket: EXE 503 Service Unavailable after step 1

installer/dup-installer/views/view.s1.base.php
Trello card: https://trello.com/c/SSga9aIC
=> LT: EXE Display low disk space warning message

installer/dup-installer/classes/utilities/class.u.notices.manager.php, installer/dup-installer/ctrls/ctrl.s3.php
=> wp-confg exception critical error report added

installer/installer.tpl
Trello task: https://trello.com/c/8tZjhGQQ
=> LT: PR Ticket: I can't get my website to restore

installer/dup-installer/classes/utilities/class.u.notices.manager.php, installer/dup-installer/views/view.s4.php
NOTICE item open prop added
add open and priority to final notice report
=> LT: EXE Step 4 UI formatting

classes/class.archive.config.php, classes/package/class.pack.installer.php, define.php, installer/dup-installer/classes/Crypt/Base.php, installer/dup-installer/classes/Crypt/Random.php, installer/dup-installer/classes/Crypt/Rijndael.php, installer/dup-installer/classes/class.csrf.php, installer/dup-installer/main.installer.php, installer/dup-installer/views/duplicator.php, installer/dup-installer/views/view.s1.base.php, installer/installer.tpl
Trello card: https://trello.com/c/njL4HyRl
=> LT: EXE - Store CSRF Token in encrypted cookie to make more secure

classes/package/class.pack.php, installer/dup-installer/classes/Crypt/Random.php, installer/dup-installer/classes/config/class.constants.php, installer/dup-installer/classes/utilities/class.u.php, installer/dup-installer/main.installer.php, installer/installer.tpl, lib/dup_archive/daws/daws.php, lib/dup_archive/tester/datester.php, lib/snaplib/class.snaplib.u.util.php
Trello card: https://trello.com/c/q5kQST4X
=> LT Ticket: Memory Issue

lib/snaplib/class.snaplib.u.util.php
Card: https://trello.com/c/F0VwKXCE
=> LT: Define custom _wp_json_sanity_check

installer/dup-installer/classes/utilities/class.u.notices.manager.php
Trello card: https://trello.com/c/76Ilg6V2
=> LT: Use of undefined constant DUPX_NOTICE_ITEM

classes/class.constants.php, classes/package/class.pack.archive.zip.php, duplicator.php
Trello card: https://trello.com/c/lYsrH1fC
=> LT: Issue: A Zip Archive is taking backup of only db

installer/dup-installer/classes/utilities/class.u.php, installer/dup-installer/ctrls/ctrl.s3.php
unicode chars ok
{$ sequence escaped
=> db pass escape function added

installer/dup-installer/ctrls/ctrl.s2.base.php
Trello card: https://trello.com/c/rb9udM35
=> LT: PR Ticket: Extraction of a big Backup failed

views/packages/main/s2.scan3.php
Card: https://trello.com/c/i3ozmps9
=> LT: LT Ticket: Duplicate database row listing

installer/dup-installer/views/view.s4.php
Card: https://trello.com/c/G2jmRKME
=> LT EXE: utf8_decode fallback function

installer/dup-installer/views/view.s4.php, views/tools/controller.php
Card: https://trello.com/c/6ock1eZx
=> PR Ticket: Post install leads to Forbidden page

assets/css/modal.css, deactivation.php
card: https://trello.com/c/EhodcAjr
=> LT: Deactivation Feedback part 2

assets/css/modal.css, deactivation.php
card: https://trello.com/c/EhodcAjr
=> LT: Deactivation Feedback part 3

installer/dup-installer/classes/class.csrf.php, installer/dup-installer/main.installer.php, installer/installer.tpl
card: https://trello.com/c/U9wOQFE7
=> LT: An invalid request was made to ‘step1’

installer/dup-installer/classes/utilities/class.u.html.php
- Auto reload start disabled
- Key escape to close lightbox enabled
=> - Bug fixed on lighbox link for target blank

classes/package/class.pack.installer.php, installer/dup-installer/classes/class.installer.state.php, installer/dup-installer/ctrls/ctrl.s3.php, installer/dup-installer/views/view.s2.basic.php, installer/dup-installer/views/view.s3.php, lib/config/class.wp.config.tranformer.php, lib/config/class.wp.config.tranformer.src.php
card: https://trello.com/c/nncfCwGx
=> LT: Clear out sensitive database connection information from wp-config.php files that are being stored in the archives

installer/dup-installer/assets/inc.css.php, installer/dup-installer/classes/class.engine.php, installer/dup-installer/classes/class.logging.php
engine log improved
loggin class updated
=> engine log improved

classes/package/class.pack.database.php
card: https://trello.com/c/0LATa0hC
=> LT: PR Ticket: not completing backup

installer/dup-installer/assets/inc.css.php, installer/dup-installer/ctrls/ctrl.s2.dbtest.php, installer/dup-installer/views/view.s2.dbtest.php
card: https://trello.com/c/HP4HF02U
=> LT: GTID consistency issue

classes/package/class.pack.installer.php
Card: https://trello.com/c/V3c90K5D
=> LT: Package creation is not working in a InstantWP

installer/dup-installer/assets/inc.css.php, installer/dup-installer/classes/class.engine.php, installer/dup-installer/classes/config/class.conf.srv.php, installer/dup-installer/classes/utilities/class.u.html.php, installer/dup-installer/classes/utilities/class.u.notices.manager.php, installer/dup-installer/ctrls/ctrl.s3.php, installer/dup-installer/main.installer.php, installer/dup-installer/views/view.s4.php
This pull request aligns the 
notice manager and html classes to the PRO
it is preparatory for subsequent modifications.
=> 20190512 al lt exe notice manager long msg pre mode and html utils update

installer/dup-installer/classes/class.installer.state.php, installer/dup-installer/classes/class.logging.php, installer/dup-installer/classes/class.password.php, installer/dup-installer/classes/config/class.boot.php, installer/dup-installer/main.installer.php
This PR improves error handling during installer initialization.
Now no information is lost and all errors are written to the log
=> 20190511 al lt die main installer problem and dawn.php ajax call

installer/dup-installer/assets/inc.css.php, installer/dup-installer/classes/utilities/class.u.html.php, installer/dup-installer/views/view.init1.php, installer/dup-installer/views/view.s1.base.php, installer/dup-installer/views/view.s2.basic.php, installer/dup-installer/views/view.s3.php
obscure password toggle added
some minor layout improvements
=> LT: Hide all input passwords with show/hide button

ctrls/ctrl.package.php
card: https://trello.com/c/2D1rLXw6
=> LT: Improve deletion logic to delete all files prefixed with name hash

classes/host/class.wpengine.host.php, classes/package/class.pack.installer.php, classes/package/class.pack.php, duplicator.php
card: https://trello.com/c/e9H9BiU1
=> LT: Detect WP Engine hosting and change the installer name

classes/class.settings.php, classes/host/class.wpengine.host.php, classes/package/class.pack.archive.php, duplicator.php, views/packages/main/s3.build.php
card: https://trello.com/c/e9H9BiU1
=> LT: Detect WP Engine hosting and its compatible changes

classes/package/class.pack.archive.zip.php, define.php
card: https://trello.com/c/jqGz9x4C
=> Memory problem on zip archive

deactivation.php
card: https://trello.com/c/ZE87czMb
=> LT: Remove tracking of the 'temporarily deactivating' reason

classes/host/class.godaddy.host.php, classes/host/class.wpengine.host.php, duplicator.php
card: https://trello.com/c/kVQNFsqa
=> LT: Auto select duparchive when installed on GoDaddy

duplicator.php
card: https://trello.com/c/nltaRSVs
=> LT: Package field type change

classes/utilities/class.u.php, installer/dtoken.php, uninstall.php
card: https://trello.com/c/7Vv9ZaZL
=> LT: Remove dtoken.php references

classes/package/class.pack.php, lib/snaplib/class.snaplib.u.util.php
card: https://trello.com/c/GqCuTCFT
=> LT: Make build % work to the tenth of a percent

installer/dup-installer/classes/class.http.php, installer/dup-installer/classes/config/class.constants.php, installer/dup-installer/index.php, installer/dup-installer/main.installer.php, installer/installer.tpl
card: https://trello.com/c/f1XDGlZi
=> LT: Bug: Installer doesn't work with the ngrok url

installer/dup-installer/views/view.s3.php
card: https://trello.com/c/mAYFuQQK
=> LT: Bug: Saved password create the issue in the installer step 3

installer/dup-installer/main.installer.php
card: https://trello.com/c/T0SESY2c
=> LT: Installer console error

installer/installer.tpl
card: https://trello.com/c/enw0WNUr
=> LT-EXE: Highlight differences in name of archive when wrong archive used

installer/dup-installer/classes/config/class.conf.srv.php
=> backupExists fixed

classes/class.logging.php, classes/utilities/class.u.php, ctrls/class.web.services.php, ctrls/ctrl.package.php, ctrls/ctrl.tools.php, ctrls/ctrl.ui.php, deactivation.php, installer/installer.tpl, views/packages/controller.php, views/packages/main/controller.php, views/settings/controller.php, views/tools/controller.php
This PR adds the error handler to the wordpress installer and admin so that PHP errors are always written to the log.
In the installer some classes have been moved from before the bootstrap class to after to align the file with the PRO version and improve readability.
=> 20190623 al lt improve log PHASE 1

classes/class.settings.php
card: https://trello.com/c/A30W5RCq
=> LT: When ziparchive and shellzip not available, auto select DupArchive for build

installer/installer.tpl
=> max size archive check FIXED

installer/installer.tpl
card: https://trello.com/c/enw0WNUr
=> LT-EXE Improve: Highlight differences in name of archive when wrong archive used

installer/dup-installer/classes/class.package.php, installer/dup-installer/classes/class.s3.func.php, installer/dup-installer/classes/class.view.php, installer/dup-installer/ctrls/ctrl.s1.php, installer/dup-installer/main.installer.php, installer/dup-installer/views/view.s1.base.php
card: https://trello.com/c/jANM5eV6
=> LT: PR Ticket: Archive not found message in step 1

installer/dup-installer/classes/class.package.php, installer/dup-installer/ctrls/ctrl.s1.php
=> 20190712 al lt add static at dupx packages functions

installer/dup-installer/ctrls/ctrl.s2.dbinstall.php
card: https://trello.com/c/VhN93rsQ
=> LT: Remove error word from the "Database Table row count validation errot

installer/dup-installer/classes/class.csrf.php, installer/installer.tpl
card: https://trello.com/c/hDsCcfTZ
=> LT: Add comment for DUPX_CSRF

classes/package/class.pack.php
card: https://trello.com/c/SMMVn4AM
=> LT:PR Ticket: Archive Creation Time is shown wrong

classes/ui/class.ui.notice.php, duplicator.php, installer/dup-installer/classes/class.s3.func.php, installer/dup-installer/classes/utilities/class.u.php, installer/dup-installer/views/view.s3.php
card: https://trello.com/c/zBM7s70z
=> LT: LT/PR Tickets: WPBakey page builder issue after migration

classes/class.settings.php, duplicator.php, views/settings/general.php
card: https://trello.com/c/RjjqLzmW
=> LT: Unhook plugins in admin

classes/package/class.pack.database.php, classes/package/class.pack.php
card: https://trello.com/c/lDzLlBc5
=> LT: Improve DB Validation

classes/utilities/class.u.php
card: https://trello.com/c/relWvpNR
=> LT: A Package download button is disabled in HomeStead

classes/class.settings.php
card: https://trello.com/c/jj1404Fs
=> LT Ticket: Notice: Undefined index: version in duplicator\classes\class.settings.php on line 28

classes/package/class.pack.database.php, classes/utilities/class.u.php, views/packages/main/s1.setup2.php
card: https://trello.com/c/aUk4pnFG
=> LT: PR Ticket: Backup Failed - Table doesn't exist

classes/utilities/class.u.php, views/tools/diagnostics/inc.settings.php
card: https://trello.com/c/d2Cjs9cs
=> LT Ticket: After migration warnings

classes/utilities/class.u.zip.php
card: https://trello.com/c/AxXESZ3c
=> LT: ZipArchive Package mode produces erroneous package in the HomeStead Environment

define.php, duplicator.php
card: https://trello.com/c/xSIDq1y7
=> LT: Temporarily Disable Questionaire

installer/installer.tpl
card: https://trello.com/c/dukeOmCU
=> LT: PR Ticket: 64-bit SO: too large for 64-bit PHP

views/settings/about-info.php
card: https://trello.com/c/ZBWEUK7Q
=> LT: Remove Google Plus social icon

installer/dup-installer/assets/inc.libs.css.php, installer/dup-installer/classes/config/class.boot.php, installer/dup-installer/classes/config/class.conf.srv.php, installer/dup-installer/classes/config/class.constants.php, installer/dup-installer/classes/utilities/class.u.php, installer/dup-installer/main.installer.php
card: https://trello.com/c/bR5iJRv2
=> LT: Port Lite design pattern in Other parts of the LITE

ctrls/ctrl.package.php
card: https://trello.com/c/hjWJ3CaO
=> LT: Display a correct error message for memory error on package creation

classes/package/class.pack.php
card: https://trello.com/c/cQRQkRnF
=> LT: Timezone related issue - Third Party plugin conflict

assets/js/javascript.php, classes/ui/class.ui.viewstate.php, ctrls/ctrl.ui.php, views/packages/details/detail.php
card: https://trello.com/c/iFQKEesR
=> LT: Packages Detail Page - Sticky

classes/package/class.pack.archive.zip.php, classes/package/class.pack.database.php, classes/package/class.pack.installer.php, classes/package/duparchive/class.pack.archive.duparchive.php, ctrls/ctrl.package.php
card: https://trello.com/c/xVcEK7Mi
=> LT Ticket: Won't make full Archive

classes/utilities/class.u.php
card: https://trello.com/c/W2Bspmqi
=> LT Ticket: Archive download issue

installer/dup-installer/views/view.s3.php
=> Increase timeout milliseconds to clean username and password in in the installation step 3

installer/dup-installer/views/view.s1.base.php
card: https://trello.com/c/34u4bhwC
=> LT: Undefined error in the installer step 1

lib/snaplib/class.snaplib.u.io.php
card: https://trello.com/c/Nq74fNCl
=> LT: Large site build problems due to 32 bit not being reported properly

duplicator.php
card: https://trello.com/c/h3XAySO9
=> LT: Menu Color Fix

define.php, duplicator.php, views/packages/details/detail.php
card: https://trello.com/c/mwO8OWNx
=> LT: Installer.php not downloading when using the link from package details page

classes/package/class.pack.php, views/packages/main/s2.scan3.php
card: https://trello.com/c/kBgnKvf7
=> LT*: Display error: User has insufficient privileges to SHOW CREATE FUNCTIONCTION

views/packages/main/s3.build.php, views/settings/general.php, views/settings/gopro.php
card: https://trello.com/c/FmNr0Oxi
=> LT*: Address UI issues caused by WordPress 5.3

define.php, duplicator.php, views/packages/details/detail.php
card: https://trello.com/c/EH1qyRoE
=> LT: Daf link issue

classes/package/class.pack.database.php
card: https://trello.com/c/XMfLhIgB
=> LT BUG: Not throwing error If table query fails

views/packages/details/controller.php
card: https://trello.com/c/cyVmPsGY
=> LT: Package button margin issue in package detail screen

classes/package/class.pack.php, views/packages/main/s2.scan3.php
card: https://trello.com/c/Bt91DM4J
=> LT: Correct error where the user has insufficient privileges to SHOW CREATE FUNCTION

ctrls/class.web.services.php, views/packages/details/detail.php
card: https://trello.com/c/ydW0AwIf
=> LT: Shared package and installer link is not working when the user is not logged in

classes/package/class.pack.installer.php, define.php, installer/dup-installer/classes/class.package.php, installer/dup-installer/classes/config/class.conf.srv.php, installer/dup-installer/views/view.help.php, installer/dup-installer/views/view.s1.base.php
card: https://trello.com/c/TU1EaPB3
=> LT: Add .htaccess file like .htaccess__[HASH] in the archive

classes/class.server.php, classes/package/class.pack.archive.php, classes/package/class.pack.database.php, classes/package/class.pack.installer.php, classes/package/class.pack.php, classes/utilities/class.u.php, ctrls/ctrl.tools.php, define.php, duplicator.php, helper.php, views/packages/main/s1.setup1.php, views/packages/main/s1.setup2.php, views/packages/main/s2.scan1.php, views/packages/main/s2.scan3.php, views/tools/diagnostics/inc.settings.php, views/tools/diagnostics/inc.validator.php, views/tools/diagnostics/information.php
card: https://trello.com/c/S8OQAP87
=> LT: HOMEPATH and ABSPATH are different in typical situation

helper.php
card: https://trello.com/c/pJpxLnIH
=> LT: Correct home path issue for ovh hosting

uninstall.php, views/tools/diagnostics/information.php
card: https://trello.com/c/7DgErMSo
=> LT: Fix the issues of 1.3.26

classes/package/class.pack.database.php, classes/package/class.pack.php, ctrls/ctrl.package.php, views/packages/main/s3.build.php
check on popen mysqldump fail added
improved error handling when creating the zip package
=> check mysqldump fail

views/packages/main/s1.setup1.php
Ticket: https://trello.com/c/2YTuVcXV
=> LT Ticket: Requirements: Fail

views/packages/main/s2.scan1.php, views/packages/main/s2.scan2.php
Card: https://trello.com/c/rpFnsDp8
Changes Screenshot: https://nimb.ws/eQYoi0
=> LT: Improve MU no support msg

assets/css/global_admin_style.css, assets/js/global-admin-script.js, assets/js/javascript.php, classes/ui/class.ui.notice.php, classes/utilities/class.u.php, ctrls/class.web.services.php, duplicator.php
card: https://trello.com/c/5RnkOvCC
=> LT: Find a way to dismiss messages.

duplicator.php
card: https://trello.com/c/uNpUQvWe
=> LT: New Upgrade Link

duplicator.php
card: https://trello.com/c/Dr038GsN
=> LT: Package can't be created in the WPEngine

classes/class.server.php
card:https://trello.com/c/I6ACw2LN
=> LT: improve log for requirements function

installer/installer.tpl
card: https://trello.com/c/fl7yrvTy
=> If the Package Hash and Archive file name doesn't match error, Display error in installer.php

classes/utilities/class.u.php
card: https://trello.com/c/bkL0IAIS
@lifeinthegrid @bobriley @meistertigran @andreamk The test procedure is written at the end of the card description.
=> LT: SQL Error Log

views/tools/diagnostics/information.php
Trello Card: https://trello.com/c/DSvSVDbg/36-lt-fix-icon-fonts
=> fixed icons

installer/dup-installer/index.php, installer/dup-installer/main.installer.php, lib/snaplib/class.snaplib.u.url.php
card: https://trello.com/c/4Xj757zB
=> LT: replace request PHP_SELF with SCRIPT_NAME

classes/class.io.php, views/tools/diagnostics/information.php
card: https://trello.com/c/vnNvSVhE
=> LT: Improve performance after install
